services:
  ensoria-projecttemplate-localstack:
    container_name: "ensoria-projecttemplate-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - DB_NAME=${DB_NAME:-ensoria}
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - "./.localstack/volume:/var/lib/localstack"
      # https://docs.localstack.cloud/references/init-hooks/#lifecycle-stages-and-hooks
      - "./.localstack/init:/etc/localstack/init"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ensoria-projecttemplate-network

  ensoria-projecttemplate-rabbitmq:
    image: rabbitmq:4-management
    container_name: ensoria-mb-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ensoria-projecttemplate-network

  ensoria-projecttemplate-redis:
    image: redis:7.4-alpine
    container_name: ensoria-projecttemplate-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - ensoria-projecttemplate-network


  ensoria-projecttemplate-postgres:
    image: postgres:16-alpine
    container_name: ensoria-projecttemplate-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ensoria
      POSTGRES_USER: ensoria
      POSTGRES_PASSWORD: ensoria
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - ensoria-projecttemplate-network


networks:
  ensoria-projecttemplate-network:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local

